language: node_js
cache:
  yarn: true
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '10'
script:
  - yarn test
  - yarn run build
after_success:
  - yarn global add travis-deploy-once@4
  - travis-deploy-once "yarn run semantic-release"
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
